### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by dotronglong** [TryGhost/knex-migrator#108]
Hello all,

I just started my first personal website with Ghost, and I want to use PostgreSQL instead of MySQL. Is there any chance to support PostgreSQL whereas knex supports it?

**Comment by dotronglong** [comment]
I tried to search around for disadvantages or obstacles when trying to support PostgreSQL, but I got no luck, hence, I would like to ask which kind of problems I might face if I tried to modify knex-migrator to support PostgreSQL?

Thanks in advance,

**Comment by kirrg001** [comment]
Ghost doesn't support PostgreSQL.

**Comment by ErisDS** [comment]
Here's why: https://blog.ghost.org/dropping-support-for-postgresql/
