### ISSUE TITLE
Node v10 support: need upgrade sqlite3

### ISSUE THREAD

**Issue by zce** [TryGhost/knex-migrator#115]
refs: https://github.com/mapbox/node-sqlite3/issues/994

The sqlite3@v4.0.1 release now supports node v10: https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#401

But the current dependence is sqlite3@4.0.0

**Comment by kirrg001** [comment]
Thanks 👍 PR is welcome :)

**Comment by kirrg001** [comment]
SQlite3 was bumped in https://github.com/TryGhost/knex-migrator/commit/1ad22045e823311416f3707684c91efbd0ca2e92.

Thanks for the report 🙂
