### ISSUE TITLE
Add timestamps to migration table

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/knex-migrator#118]
```
+----+-------------------------------------------------+---------+----------------+
| id | name                                            | version | currentVersion |
+----+-------------------------------------------------+---------+----------------+
|  1 | 1-create-tables.js                              | init    | 2.18           |
|  2 | 2-create-fixtures.js                            | init    | 2.18           |
```

The migration table currently has **4 fields: id, name, version and currentVersion.**
But it does not contain a timestamp: created_at.

A `created_at` field is a default field, which any table should have.

It makes it possible to follow the execution of migration scripts.

This issue requires to extend our `runDatabaseUpgrades` helper function, which is executed everytime you call commands of knex-migrator. It's basically a mechanmis to execute database migrations within knex-migrator without using knex-migrator.

**Comment by ErisDS** [comment]
This is a nice idea, but we don't have a strong requirement for it right now. Going to close until we change our minds.
