### ISSUE TITLE
test on windows

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/knex-migrator#12]
Help wanted ;-)

**Comment by ErisDS** [comment]
cc @cobbspur 😝 🏢

**Comment by kirrg001** [comment]
I have windows 10 now as second partition. I will also help testing soon 👍

**Comment by kirrg001** [comment]
**Windows 10 gitbash**
knex-migrator init worked

Do people use something else then gitbash?

**Comment by kirrg001** [comment]
Knex-migrator is running for more than 2 years now. We haven't received any bug report from windows users so far. 

> Windows 10 gitbash
> knex-migrator init worked (sqlite3)

Closing.
