### ISSUE TITLE
Improve general log output and debug messages

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/knex-migrator#13]
This issue collects pains around log outputs or debug messaging. 

- [ ] We could transform some debug messages into info logs.
- [ ] Look at https://github.com/TryGhost/knex-migrator/issues/61
- [ ] Fix https://github.com/TryGhost/knex-migrator/issues/47
- [ ] Fix https://github.com/TryGhost/knex-migrator/issues/57
- [ ] Look at https://github.com/TryGhost/knex-migrator/issues/13#issuecomment-257318640.

**Comment by ErisDS** [comment]
There's some extra stuff to consider here around production / development mode.

I've just run `npm start --production` on an alpha Ghost build. Hidden away in the error log is the notice that I need to run `knex-migrator init`, but that doesn't actually help me! So there are a couple of TODOs please:

- [ ] Update the messaging to be clearer about what knex-migrator is, and how to use it
- [ ] Ensure the messaging is relevant to the user's environment
- [ ] Ensure DatabaseIsNotOkError's result in some stdout messaging as well as logs? Maybe by doing something with `process.stdout.isTTY` ?

**Comment by kirrg001** [comment]
> I've just run npm start --production on an alpha Ghost build. Hidden away in the error log is the notice that I need to run knex-migrator init, but that doesn't actually help me! 

Usually your case should not happen, because Ghost-CLI should manage the db initialisation for you automatically. Plus you have used `npm start` and not `ghost start`.

But in general this behaviour is absolutely expected. If you run production mode and you are using the default configuration (which is file only), we log all errors into files and not to stdout. That's why we should connect Ghost-CLI to be able to execute `ghost logs` to get more transparency and to get an easy access to your logs (doesn't matter if stdout or file). See https://github.com/TryGhost/Ghost-CLI/issues/42

> Maybe by doing something with process.stdout.isTTY

Could you expand your idea please?

**Comment by ErisDS** [comment]
I have found recently a few times, that Ghost doesn't start and tells me to run `knex-migrator init`. I run `knex-migrator init`, which then says it is ok, but Ghost still doesn't start & tells me to run it again. 

We possibly need to either rethink the error message, or make init also run the health check?

**Comment by kirrg001** [comment]
Hmmm this happened to me once when i've mixed env's. If you can figure out steps to reproduce, that would be great. Let me know here.

> We possibly need to either rethink the error message, or make init also run the health check?

The init command does an integrity check and based on the result, it initialises or not.
The same function is used for the health check. We could reconsider the messaging.

**Comment by ErisDS** [comment]
Haven't had any recent issues with logs, output or debug. Closing until we do 😬
