### ISSUE TITLE
migrations with timezones?

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/knex-migrator#16]
Given that we had this before, I was just wondering - will it be possible for knex-migrator to properly handle timezones?

I'm thinking of the overrides file in Ghost, which will now not be required before doing migrations?

**Comment by kirrg001** [comment]
If Ghost needs to require the overrides file, then Ghost can do that in the before hook. 
Knex-migrator doesn't do anything with dates. It just delegates the command back to Ghost. 

Closing this now - we can re-open if we experience trouble 👍
