### ISSUE TITLE
Escape db name in DB creation

### ISSUE THREAD

**Issue by acburdine** [TryGhost/knex-migrator#22]
Currently there is a database creation issue with the migrator in that database names that contain certain special characters (for instance, the `-` in `ghost-production`) generate an error on database creation.

Easy fix: ensure the db name in the sql statement is wrapped in backticks, which is the mysql way to sanitize database names.

**Edit:** another good thing to do would be to add an `IF NOT EXISTS` clause to the db creation statement, which means an error would not be thrown at all (still would probably be good to have the catch there)

**Comment by kirrg001** [comment]
> Currently there is a database creation issue with the migrator in that database names that contain certain special characters (for instance, the - in ghost-production) generate an error on database creation.

Hmm i prefer changing the config files to use `_` (underscores) for db names?
If we sanitise the name, we would create an inconsistency?What do you think?

> Edit: another good thing to do would be to add an IF NOT EXISTS clause to the db creation statement, which means an error would not be thrown at all (still would probably be good to have the catch there)

This logic exists already, see https://github.com/TryGhost/knex-migrator/blob/master/lib/database.js#L57

**Comment by acburdine** [comment]
> This logic exists already, see https://github.com/TryGhost/knex-migrator/blob/master/lib/database.js#L57

I understand it's already there, but why have an error thrown at all if it could be avoided?

> Hmm i prefer changing the config files to use _ (underscores) for db names?
If we sanitise the name, we would create an inconsistency? What do you think?

What do you mean by an inconsistency? Sanitizing was an incorrect term, I really meant escaping. Also - this could potentially be vulnerable to sql injection if someone specified a specific value in their database name. (Not that that's a huge issue though, as it would require access to the server). Ultimately I think it's just best practice to escape the db name - as I'm sure knex itself probably does it automatically for regular queries.

**Comment by kirrg001** [comment]
> I understand it's already there, but why have an error thrown at all if it could be avoided?

There was a reason why, but i don't remember. I think the reason was that knex somehow returns a weird response when using `IF NOT EXIST`.

If you can ensure testing all cases, then you can remove the error handling and add `IF NOT EXIST` 👍  This would be a good optimisation.

 > What do you mean by an inconsistency?

If you define in your config file: `database: {connection: {database: 'ghost-something'}}` then you expect that this database name get's created and not `ghost_something`. That's why i would rather change the affected config files and optimise the error handling if needed.

> Also - this could potentially be vulnerable to sql injection if someone specified a specific value in their database name

How is this possible?Can you explain?
We are reading the values from your config. Then someone needs to have access to your server. 

>  I think it's just best practice to escape the db name

If it's best practise, then sure let's add it. I am not against it :) just trying to understand.

**Comment by acburdine** [comment]
Ok - I think we've clarified the confusion now 😄.

I don't believe there would be any knex issues with the `if not exists` statement - but I will leave that part out for the moment until we have true integration testing of the migration tool.

As far as the backticks, there wouldn't be an inconsitency - I misspoke earlier by saying sanitization, when I really meant escaping. Knex-migrator would not change the provided db name in any way - this change ensures that it is able to work with any valid mysql database name that is passed in.

Will update the PR and then we should be good to go :)

**Comment by ErisDS** [comment]
Just to clarify here - we are not using `-` in a default anywhere are we?

**Comment by ErisDS** [comment]
> I think it's just best practice to escape the db name
I'm not sure if you mean best practice as in "the community approved solution" or as in "the best option here" - those are quite different things :wink: 

I want to impress that using a DB name that requires escaping, whilst possible, is very, very undesirable. Take it from someone who has spent years having to add backticks to their SQL queries. Therefore it is, IMO, extremely important that we do not have this as a default and that we try to avoid it if possible. 

If we are creating a DB for a user, and the name requires escaping, I'd suggest that's worthy of a prompt to the user to confirm. For now, that can be a feature request logged for future though :)

**Comment by acburdine** [comment]
@ErisDS in some local edits to Ghost-CLI I had `-` as a default - will change to an underscore. But regardless, if someone puts a `-` in their database name it would be good to not throw an error :)
