### ISSUE TITLE
knex-migrator and env's

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/knex-migrator#24]
`knex-migrator init` will init your database with default env (which is mostly development)
`NODE_ENV=production knex-migrator init` will init your database with production env.

Think about a smart way.

**Comment by ErisDS** [comment]
Tonight I ran `knex-migrator reset`, when I meant to run `NODE_ENV=production knex-migrator reset`.

Maybe the reset command needs a confirm step? 

E.g. it says "this will reset the sqlite db ghost-dev.db: Y/n" or "this will reset the MySQL db ghost_prod: Y/n"

Just an idea to prevent future pain 😄

**Comment by kirrg001** [comment]
yeah good idea 👍

**Comment by kirrg001** [comment]
Might be worth to consider the following notation:

`knex-migrator reset --dev`
`knex-migrator reset --development`
`knex-migrator reset --prod`
`knex-migrator reset --production`

**Comment by ErisDS** [comment]
We haven't run into this as an issue recently. Closing until it becomes a problem 😅
