### ISSUE TITLE
Rolling back due to an error runs all pending migrations in reverse

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/knex-migrator#241]
### Issue Summary

The situation I've seen is one in Ghost and related to https://github.com/TryGhost/Ghost/issues/12589.

In the event of a rollback due to an error, knex-migrator will reverse the full list of migrations it was meant to apply and run their `down` functions. This isn't correct because we shouldn't be running the `down` functions of migrations we haven't ran the up for yet.

### To Reproduce

I'm pulling this example from the issue:

1. Start with a DB in 2.27 state
2. Attempt to migrate up to 3.41
3. A migration in 2.28 will fail due to a code error
4. We expect it to rollback 2.28 migrations. Instead, 3.41, 3.40, 3.39... migrations will run first

If some incorrect DB assumptions are made in the `down` functions of those 3.x migrations, they'll possibly also fail when rolling back, which makes the situation even worse given we didn't even want to do that. Also, the error then given would be for the 3.x rollback problem, rather than the original cause for the rollback.

I'd expect it to rollback any versions where it has either successfully migrated to that version, or was part-way through that version before seeing an error.

### Technical details:

* `knex-migrator`: 3.5.0

**Comment by daniellockyer** [comment]
Note: in Ghost we're now enforcing `most recent version of a major -> latest version`, so my example might not work. But the issue still stands in knex-migrator.

**Comment by allouis** [comment]
Closed by https://github.com/TryGhost/knex-migrator/commit/b4c6ae7504bb1755bd10fb3f57e2b556c7772e7c
