### ISSUE TITLE
DigitalOcean managed DB requires primary key on all tables

### ISSUE THREAD

**Issue by surdaft** [TryGhost/knex-migrator#247]
Digital Ocean are requiring that all databases use a primary key, due to how their database backups work. This has been raised in the upstream knex project (https://github.com/knex/knex/issues/4141) however I feel it also relates to how the migrator works.

I encountered this issue when creating a new ghost instance and the migrations_lock table could not be created, as it does not contain a primary key.

I'm not sure how the best solution should work, for now I will see if I can modify the node_modules to inject `set sql_require_primary_key=0` before any query and `set sql_require_primary_key=1` after, to ensure they atleast migrate.

**Comment by matthanley** [comment]
Closing as a dup of https://github.com/TryGhost/knex-migrator/issues/251 (this issue is older, but the linked issue has more context)
