### ISSUE TITLE
mysql port

### ISSUE THREAD

**Issue by Superman-wc** [TryGhost/knex-migrator#26]
lib/database.js line 50
connection: {
            host: dbConfig.connection.host,
            user: dbConfig.connection.user,
            password: dbConfig.connection.password
        }

port ?

connection: {
            host: dbConfig.connection.host,
            user: dbConfig.connection.user,
            password: dbConfig.connection.password,
            port: dbConfig.connection.port
        }

mysql port not is default 3306 !!!!

**Comment by kirrg001** [comment]
@Superman-wc Thanks for your report. I will push a fix next week 👍
