### ISSUE TITLE
Removing init scripts does not work

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/knex-migrator#48]
Adding more init scripts works nice.
Removing init scripts does not work. Will throw an error.

**We need to think about the following questions**
1. Should it be possible to re-run an init script?`knex-migrator init --force`
2. Removing init scripts does not work - why is that?

**Comment by kirrg001** [comment]
> Removing init scripts does not work - why is that?

This needs investigation. I have never investigated.

**Comment by ErisDS** [comment]
We have never run into this as an issue. Closing until it becomes a problem 😅
