### ISSUE TITLE
Too specific versions in package.json causing bloat

### ISSUE THREAD

**Issue by spion** [TryGhost/knex-migrator#53]
The versions as specified here:

https://github.com/TryGhost/knex-migrator/blob/master/package.json#L35

are too exact. It contributes at least 2 extra copies (one from knex-migrator, one from knex) to bluebird being installed 6 times and  lodash 14 times when installing ghost.

edit: lodash copies in ghost
![lodash in ghost](https://pbs.twimg.com/media/C4D_FvXWYAA8A8n.png)

**Comment by kirrg001** [comment]
Hey @spion 🙃

Thanks for your report.
We will look into this soon 👍

**Comment by kirrg001** [comment]
Thanks again for your report!

You are absolutely right about the `lodash` dependency, but i won't do anything against it right now. Having lot's of specific `lodash` version doesn't slow down bootstrapping. It might be that the installation is a little bit slower -  i haven't checked that yet.

**But** your report lead me to make a different dependency more relaxed, it's [Ignition](https://github.com/TryGhost/Ignition). Ignition is used in multiple projects Ghost depends on and this slowed down the Ghost bootstrap by 500ms!

**Comment by spion** [comment]
@kirrg001 Thats okay, I don't personally mind it. I just saw someone on twitter make fun of the 200MB installs and decided to dig in further, hoping that maybe we can fix this node modules issue!

I think this isn't really Ghost's fault, and the pinned versions are just a drop in the bucket. The real problem is the node_modules resolution algorithm. If there are 6 modules that depend on lodash v3, and 5 modules that depend on lodash v4, then lodash v3 will be deduplicated and have only one copy living in node_modules. However, lodash v4 will still have 5 distinct copies, each living in the separate node_modules directories of the respective dependants. Even if the copies are identiacal, yarn and npm cannot deduplicate them.

The proper solution for this is to use some sort of "symlinking" mechanism (either native or based on metadata files)

**Comment by kirrg001** [comment]
I've updated the versions to be less strict, see https://github.com/TryGhost/knex-migrator/commit/7125d169cc499fe6af4e6136c431a73540cc2493

Thanks again!
