### ISSUE TITLE
No error shown for unknown commands

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/knex-migrator#57]
I fat fingered the `init` command just now, instead running `knex-migrator int`. Instead of an error saying that the command was not found (or outputting the help docs) there was a silent exit, if I didn't know that there should be more output I would have thought the command was successful.

**Comment by kirrg001** [comment]
Thanks 👍

**Comment by kirrg001** [comment]
Added a sub task to https://github.com/TryGhost/knex-migrator/issues/13.

> Improve general log output and debug messages
