### ISSUE TITLE
How can I possibly know the current version for a new database?

### ISSUE THREAD

**Issue by Bilge** [TryGhost/knex-migrator#73]
I just want to create a new SQLite database so I can actually run Ghost, but this is not possible.

* If I run `knex-migrator init` without a `currentVersion` key I get "MESSAGE: MigratorConfig.js needs to export the a current version."
* If I run `knewx-migrator init` with `currentVersion: 1` (or any other value) I get "INFO Finished database init!", but when starting Ghost I get:

>Unhandled rejection DatabaseIsNotOkError: Please run knex-migrator init

And so the cycle continues endlessly. I do not understand how I am supposed to know the current version for a database that doesn't exist yet. Why does `knex-migrator init` want a `currentVersion` key and what am I supposed to set it to so I can create a new SQLite database that will work with Ghost?

**Comment by ErisDS** [comment]
@Bilge It was many years ago, but you have been spoken to about use of tone when interacting with my team before, this as a reminder to be constructive. 

The issue above doesn't include any information that would allow me to understand how the situation was reached, therefore I'm only able to point you at the docs for installing Ghost. There are a set of options for how to install Ghost is here: https://docs.ghost.org/docs/getting-started-guide.

Following the method that applies to you from that page should not lead to the situation you describe. If you still end up encountering a bug with knex-migrator, please raise a bug report that includes reproduction steps and the technical details of your system.

**Comment by Bilge** [comment]
I don't understand what you mean by tone. I don't know any members of your
team, nor do I recall the past incident to which you refer, so I have no
motivation to make personal attacks, nor do I believe to have done do.

Unfortunately I cannot say the same for yourself. It seems to me that if
anyone is taking such a tone it would be you because you have some
unresolved issue with me. Considering I've already forgotten about it I
recommend you try to do the same. If that's not possible I'm willing to
talk about it but respectfully request you do so in an equally respectful
and constructive way.

I only posted this issue for our mutual benefit, so I could understand how
to format this file and so you might see value in updating the
documentation so your project may be improved.

**Comment by miaozeyu** [comment]
@Bilge Hi, I had the same question when I ran knex-migrator init command: how am I supposed to know the current version number if the database doesn't exist yet? I also don't understand what's the "subfolder" parameter. 
Were you ever able to figure it out? Much appreciated!

**Comment by Bilge** [comment]
I actually did figure it out, but in the spirit of the maintainers of this repository, I'm not interested in helping anyone out.

**Comment by LukeXF** [comment]
My MigratorConfig.js file (copied from your guide) has an error in it.

What should I put for `subfolder: 'upgrades'  [default: versions]`. I think that's the same problem @miaozeyu had.

**Comment by LukeXF** [comment]
`MigratorConfig.js needs to export the a current version.` what should I put here, as it's not clear
