### ISSUE TITLE
KnexMigrator.init doesn't exit on its own

### ISSUE THREAD

**Issue by acburdine** [TryGhost/knex-migrator#8]
When running KnexMigrator init programmatically, the process doesn't exit on its own.

Removing this finally call here https://github.com/TryGhost/knex-migrator/blob/master/bin/knex-migrator-init#L32 also causes `knex-migrator init` to not exit on its own.

**Comment by kirrg001** [comment]
I can still see sometimes problems with destroying the connection.
See https://github.com/tgriesser/knex/issues/1752

**Comment by kirrg001** [comment]
Downgraded knex to `0.12.2`, so the problem should not appear with knex-migrator.
Still, leaving this issue open for now.

**Comment by kirrg001** [comment]
I can see it some times. Will investigate tomorrow.
