### ISSUE TITLE
Production Migrator not working

### ISSUE THREAD

**Issue by cristiandley** [TryGhost/knex-migrator#80]
In my local migrator works, but in production ot working.

The issue is... that i run the `knex-migrator migrate` it says everything is fine ready... but when i deploy the docker it shout on my error log:

`InternalServerError: Please provide a file named MigratorConfig.js in your project root.`

Any idea about this ?

i have `MigratorConfig.js` on my root...

**Comment by kirrg001** [comment]
Sounds like you execute `knex-migrator` not in your root directory.
Please double check and if not, you can use `--mgpath <path-to-MigratorConfig.js>`

**Comment by cristiandley** [comment]
Sorry i didnt closed, the issue was a Typo on `MigratorConfig.js`
