### ISSUE TITLE
Migration error - MigratorConfig.js not found

### ISSUE THREAD

**Issue by MaluNoPeleke** [TryGhost/knex-migrator#90]
I use Ghost on a hoster which doesn't allow ghost-cli to be installed. 
That's why I came up with [my own upgrade script](https://www.peleke.de/ghost-1-0-aktualisierung-bei-uberspace/). This worked successful until the update of Ghost 1.16 to 1.18.
Now I always get the following error:

> NAME: InternalServerError
> MESSAGE: Please provide a file named MigratorConfig.js in your project root.

Even if I use  `NODE_ENV=production knex-migrator migrate --mgpath /home/peleke/node_apps/ghost/`.
There is a MigratorConfig.js in that directory with correct permissions (644).
How can I update properly to the new Ghost version without ghost-cli?

**Comment by kirrg001** [comment]
Hey 👋

Which version of the knex-migrator is installed?

**Comment by MaluNoPeleke** [comment]
1.3.0 and node.js 8.9.1

**Comment by kirrg001** [comment]
`--mgpath` was added in knex-migrator 2.x.

**Comment by MaluNoPeleke** [comment]
@kirrg001 Sorry, I was confused about ghost-cli 1.3.0.
I meant **knex-migrator 2.1.9** is installed and the MigratorConfig.js is in the project root.

**Comment by kirrg001** [comment]
And the global installation `knex-migrator --version` shows 2.1.9?

**Comment by MaluNoPeleke** [comment]
Yes, exactly

**Comment by kirrg001** [comment]
What if you use the local ghost dependency?
Maybe your global binaries are not build correctly.

`/node_modules/.bin/knex-migrator-migrate`

**Comment by MaluNoPeleke** [comment]
I was able to fix it by running the whole script again but thanks for the support.
