### ISSUE TITLE
auto recover lock entry

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/knex-migrator#94]
The [lock entry](https://github.com/TryGhost/knex-migrator/blob/master/lib/index.js#L711) is important for knex-migrator to figure out the state of a lock.

**If this line is getting removed (*manually*)**, you won't be able to run a migration anymore.
We should double check the existence of this field. 

I have not find a case where this line get's removed by knex-migrator, so can only be the case of you deleting the entry. The improvement is easy to add, just a little reordering of this [line](https://github.com/TryGhost/knex-migrator/blob/master/lib/index.js#L711).

**Comment by kirrg001** [comment]
Workaround:

`insert into migrations_lock (lock_key, locked, acquired_at, released_at) values ('km01', 0, null, null);`

**Please only execute this query, if you have manually removed your lock entry.**

**Comment by ErisDS** [comment]
Not run into this recently, can reopen if it rears its head.
