### ISSUE TITLE
Make knex-migrator modular

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/knex-migrator#95]
The current code base mostly lives in a [single file with a single prototype](https://github.com/TryGhost/knex-migrator/blob/3.1.4/lib/index.js).

Knex-migrator was developed iterative and i wasn't really sure how the code base will look like in the first stages. The single file is getting more and more unreadable. 

To refactor the single file, it requires us to:

1. [ ] Transform prototype into a class (ES6)
2. [x] Come up with an idea for how to group the logic into multiple units (each unit is either a helper or a class - depending on it's tasks)
3. [ ] 100% unit test the units

To be able to fulfil (2) you have to look for common steps and responsibilities, which can form a unit.

**Comment by kirrg001** [comment]
> 2. Come up with an idea for how to group the logic into multiple units (each unit is either a helper or a class - depending on it's tasks)

@gargol and me will take a quick look at this and see if we can reduce the index.js file code and instead create some little units.

**Comment by gargol** [comment]
Above changes were regarding pt.2 and did some initial code regrouping. Noticeable change that was's just a refactoring was an introduction of internal migrations with 402f9de. Next steps would be further extracting some of the private methods (ones starging with`_` prefix) out of `index.js` module.

**Comment by ErisDS** [comment]
We always make our code better each time we work on it. Don't need to track this as an issue :)
