### ISSUE TITLE
Version numbers not being interpreted as expected

### ISSUE THREAD

**Issue by BlueHatbRit** [TryGhost/knex-migrator#97]
Hey there, I've been trying out knex-migrator (and also studying the code to look at possible postgres support). While running against a MySQL database I noticed that version numbers such as 1.0.11 is ranked as higher than 1.1.0 in the migrator.

I think this is due to the utils function isGreaterThanVersion. It will convert `1.0.11` to 1011 and `1.1.0` to 110. Then in the final check it will output that `1011 > 110`.

I think this can be fixed fairly easily using the popular library [compare-ver](https://www.npmjs.com/package/compare-ver) and just modifying the isGreaterThanVersion function to make use of the library. Alternatively a re-implementation of the library can be used, but it seems like a good fit for this usage.

I'd be happy to sit down and create a formal PR for this if the approach seems sane.

---

On a small off-topic question, how would the maintainers feel about me possibly submitting a PR with Postgres support for this module? I'm aware you do not support Postgres across your Ghost product so it may not be something you're willing to maintain, in which case a fork may be a better idea for my uses.

**Comment by kirrg001** [comment]
> I'd be happy to sit down and create a formal PR for this if the approach seems sane.

This is very welcome 👍 Thanks.

> On a small off-topic question, how would the maintainers feel about me possibly submitting a PR with Postgres support for this module? 

Sure, also welcome 👍
